<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>프로미스</title>
  </head>
  <body>
    <script>
      /* 비동기 처리의 방법
        2) Promise 이용 방법 */

      /* promise 객체 : 처리에 성공했을 때 실행할 함수, 처리에 실패했을 때 실행할 함수를 미리 약속
        1) Producer 입장
        - 성공했을 때, 실패했을 때 처리할 함수
        - new Promise(콜백함수)
            => new Promise(( resolve, reject )=>{})
            * resolve : 처리가 성공했을 때 실행
            * reject : 처리가 성공하지 못했을 때 실행 (오류났을 때 실행)
            - PromiseState : pending(대기상태, 처리 중인 상태), fulfilled(완료상태), rejected(에러상태)

        2) Consumer 입장
        - .then(함수) : 성공했을 때 then 영역에 들어옴
        - catch(함수) : 실패했을 때 catch 영역에 들어옴
        - finally() : 마지막에 무조건 들어옴
      */

      const confirm = false;
      // 1) Producer 입장 : promise 객체 생성
      const promise = new Promise((resolve, reject) => {
        if (confirm) {
          setTimeout(() => {
            resolve("성공");
          }, 3000);
        } else {
          setTimeout(() => {
            reject(new Error("error"));
          }, 3000);
        }
      });
      console.log(promise);

      // 2) Consumer 입장 : promise 객체 실행
      // promise.then(함수).catch(함수).finally(함수)
      promise
        .then((res) => {
          console.log(res);
        })
        .catch((err) => {
          console.log(err);
        })
        .finally(() => {
          console.log("끝");
        });

      /* promise 체이닝 : 값 또는 프로미스 자체를 then에게 전달 가능 => 따라서 체이닝이 가능하다 */
      const fetchNumber = new Promise((res, rej) => {
        setTimeout(() => res(1), 1000); // res(1) : 성공했을때(res) 1반환
      });

      // .then은 성공했을 때 -> 값이 넘어갈수도 있고, 객체 자체가 넘어갈수도 있다
      fetchNumber
        .then((num) => num * 2) // {} 없으니까 알아서 return 해줌
        .then((num) => num * 3)
        .then((num) => {
          return new Promise((res, rej) => {
            res(num);
          });
        })
        .then((num) => console.log(num));

      /* promise 체이닝, 오류처리 */
      // 닭 => 계란 => 계란후라이 예제

      const getHen = () => {
        return new Promise((res, rej) => {
          setTimeout(() => res("🐔"), 1000);
        });
      };
      const getEgg = (hen) => {
        return new Promise((res, rej) => {
          //   setTimeout(() => res(`${hen} => 🥚`), 1000);
          setTimeout(() => rej(`${hen} => 🥚`), 1000);
        });
      };
      const getCook = (egg) => {
        return new Promise((res, rej) => {
          setTimeout(() => res(`${egg} => 🍳`), 1000);
        });
      };

      //   getHen()
      //     .then((hen) => getEgg(hen))
      //     .then((egg) => getCook(egg))
      //     .then((cook) => console.log(cook));
      // 정상작동

      getHen()
        .then((hen) => getEgg(hen))
        .catch((err) => {
          // 오류났을 때의 처리
          return "🤣🤣";
        })
        .then((egg) => getCook(egg))
        .then((cook) => console.log(cook));
      // 체이닝이 여러개가 들어갈 경우 catch 넣어서 오류 났을 때의 처리 해주는것이 좋음
    </script>
  </body>
</html>
